services:
    ezpublish.cache_pool:
        # As we support custom TagAware services, we set class as interface here so lazy class is "correct"
        class: Symfony\Component\Cache\Adapter\TagAwareAdapterInterface
        factory: ["@ezpublish.cache_pool.factory", getCachePool]
        arguments: ["@ezpublish.config.resolver"]

    ezpublish.cache_pool.factory:
        class: Ibexa\Bundle\Core\ApiLoader\CacheFactory
        calls:
            - [setContainer, ["@service_container"]]

    Ibexa\Bundle\Core\Cache\Warmer\ProxyCacheWarmer:
        arguments:
            - '@Ibexa\Core\Repository\ProxyFactory\ProxyGeneratorInterface'
        tags:
            - { name: kernel.cache_warmer }
