services:
    ezpublish.http_kernel.reject_explicit_front_controller_requests_listener:
        class: Ibexa\Bundle\Core\EventListener\RejectExplicitFrontControllerRequestsListener
        tags:
              - { name: kernel.event_subscriber }
