services:
    # Filters
    ezpublish.image_alias.imagine.filter.unsupported:
        class: Ibexa\Bundle\Core\Imagine\Filter\UnsupportedFilter
        public: false

    ezpublish.image_alias.imagine.filter.reduce_noise.imagick:
        class: Ibexa\Bundle\Core\Imagine\Filter\Imagick\ReduceNoiseFilter
        public: false

    ezpublish.image_alias.imagine.filter.reduce_noise.gmagick:
        class: Ibexa\Bundle\Core\Imagine\Filter\Gmagick\ReduceNoiseFilter
        public: false

    # Aliasing by default to unsupported filter as it's not supported by GD.
    # Alias is changed by Imagine compiler pass to use current driver.
    ezpublish.image_alias.imagine.filter.reduce_noise:
        alias: ezpublish.image_alias.imagine.filter.unsupported

    ezpublish.image_alias.imagine.filter.swirl.imagick:
        class: Ibexa\Bundle\Core\Imagine\Filter\Imagick\SwirlFilter
        public: false

    ezpublish.image_alias.imagine.filter.swirl.gmagick:
        class: Ibexa\Bundle\Core\Imagine\Filter\Gmagick\SwirlFilter
        public: false

    ezpublish.image_alias.imagine.filter.swirl:
        alias: ezpublish.image_alias.imagine.filter.unsupported

    # Filter loaders
    ezpublish.image_alias.imagine.binary_loader:
        class: Ibexa\Bundle\Core\Imagine\BinaryLoader
        arguments: ["@ezpublish.fieldType.ezimage.io_service", "@mime_types"]
        tags:
            - { name: liip_imagine.binary.loader, loader: ibexa }

    ezpublish.image_alias.imagine.cache_resolver:
        class: Ibexa\Bundle\Core\Imagine\IORepositoryResolver
        arguments:
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@router.request_context"
            - "@liip_imagine.filter.configuration"
            - "@ezpublish.image_alias.variation_purger"
            - "@ezpublish.image_alias.variation_path_generator"
        tags:
            - { name: liip_imagine.cache.resolver, resolver: ibexa }

    ezpublish.image_alias.imagine.cache_resolver_decorator_factory:
        class: Ibexa\Bundle\Core\Imagine\Cache\ResolverFactory
        arguments:
            - '@ezpublish.config.resolver'
            - '@ezpublish.image_alias.imagine.cache_resolver_decorator.inner'
            - 'Ibexa\Bundle\Core\Imagine\Cache\Resolver\ProxyResolver'
            - 'Ibexa\Bundle\Core\Imagine\Cache\Resolver\RelativeResolver'

    ezpublish.image_alias.imagine.cache_resolver_decorator:
        class: Liip\ImagineBundle\Imagine\Cache\Resolver\ProxyResolver
        factory: ['@ezpublish.image_alias.imagine.cache_resolver_decorator_factory', 'createCacheResolver']
        decorates: ezpublish.image_alias.imagine.cache_resolver
        lazy: true

    ezpublish.image_alias.imagine.cache.alias_generator_decorator:
        class: Ibexa\Bundle\Core\Imagine\Cache\AliasGeneratorDecorator
        lazy: true
        arguments:
            - '@ezpublish.image_alias.imagine.variation.imagine_alias_generator'
            - '@ezpublish.cache_pool'
            - '@router.request_context'
            - '@Ibexa\Core\Persistence\Cache\Identifier\CacheIdentifierGeneratorInterface'
        calls:
            - [setSiteAccess, ['@ezpublish.siteaccess']]

    ezpublish.image_alias.imagine.variation.imagine_alias_generator:
        class: Ibexa\Bundle\Core\Imagine\Variation\ImagineAwareAliasGenerator
        arguments:
            - '@ezpublish.image_alias.imagine.alias_generator'
            - '@ezpublish.image_alias.variation_path_generator'
            - '@ezpublish.fieldType.ezimage.io_service'
            - '@liip_imagine'

    ezpublish.image_alias.imagine.alias_generator:
        class: Ibexa\Bundle\Core\Imagine\AliasGenerator
        arguments:
            - "@ezpublish.image_alias.imagine.binary_loader"
            - "@liip_imagine.filter.manager"
            - "@ezpublish.image_alias.imagine.cache_resolver"
            - "@liip_imagine.filter.configuration"
            - "@?logger"

    ezpublish.image_alias.imagine.alias_cleaner:
        class: Ibexa\Bundle\Core\Imagine\AliasCleaner
        arguments: ["@ezpublish.image_alias.imagine.cache_resolver"]

    Ibexa\Core\FieldType\Image\AliasCleanerInterface:
        alias: ezpublish.image_alias.imagine.alias_cleaner

    ezpublish.image_alias.imagine.placeholder_provider.configurator:
        class: 'Ibexa\Bundle\Core\Imagine\PlaceholderAliasGeneratorConfigurator'
        arguments:
            - '@ezpublish.config.resolver'
            - '@ezpublish.image_alias.imagine.placeholder_provider.registry'
            - '%image_alias.placeholder_providers%'

    ezpublish.image_alias.imagine.alias_generator.placeholder:
        class: 'Ibexa\Bundle\Core\Imagine\PlaceholderAliasGenerator'
        decorates: 'ezpublish.image_alias.imagine.alias_generator'
        configurator: ['@ezpublish.image_alias.imagine.placeholder_provider.configurator', 'configure']
        arguments:
            - '@ezpublish.image_alias.imagine.alias_generator.placeholder.inner'
            - '@ezpublish.image_alias.imagine.cache_resolver'
            - '@ezpublish.fieldType.ezimage.io_service'
        public: false

    ezpublish.image_alias.imagine.alias_generator.image_asset:
        class: 'Ibexa\Bundle\Core\Imagine\ImageAsset\AliasGenerator'
        arguments:
            - '@ezpublish.image_alias.imagine.cache.alias_generator_decorator'
            - '@ezpublish.api.service.content'
            - '@Ibexa\Core\FieldType\ImageAsset\AssetMapper'
        public: false

    ezpublish.image_alias.imagine.placeholder_provider.registry:
        class: 'Ibexa\Bundle\Core\Imagine\PlaceholderProviderRegistry'

    ezpublish.image_alias.placeholder_provider.generic:
        class: 'Ibexa\Bundle\Core\Imagine\PlaceholderProvider\GenericProvider'
        arguments:
            - '@liip_imagine'
        tags:
            - { name: 'ezpublish.placeholder_provider', type: 'generic' }

    ezpublish.image_alias.imagine.placeholder_provider.remote:
        class: 'Ibexa\Bundle\Core\Imagine\PlaceholderProvider\RemoteProvider'
        tags:
            - { name: 'ezpublish.placeholder_provider', type: 'remote' }

    ezpublish.image_alias.imagine.filter.loader.scaledown.base:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, ["@liip_imagine.filter.loader.thumbnail"]]

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.width_height:
        parent: ezpublish.image_alias.imagine.filter.loader.scaledown.base
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleDownOnlyFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaledownonly" }

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.width:
        parent: ezpublish.image_alias.imagine.filter.loader.scaledown.base
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleWidthDownOnlyFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalewidthdownonly" }

    ezpublish.image_alias.imagine.filter.loader.scaledownonly.height:
        parent: ezpublish.image_alias.imagine.filter.loader.scaledown.base
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleHeightDownOnlyFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaleheightdownonly" }

    ezpublish.image_alias.imagine.filter.loader.relative_scale:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, ["@liip_imagine.filter.loader.relative_resize"]]

    ezpublish.image_alias.imagine.filter.loader.scalewidth:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleWidthFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalewidth" }

    ezpublish.image_alias.imagine.filter.loader.scaleheight:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleHeightFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaleheight" }

    ezpublish.image_alias.imagine.filter.loader.scale:
        parent: ezpublish.image_alias.imagine.filter.loader.relative_scale
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scale" }

    ezpublish.image_alias.imagine.filter.loader.scale_exact.base:
        abstract: true
        public: false
        calls:
            - [setInnerLoader, ["@liip_imagine.filter.loader.resize"]]

    ezpublish.image_alias.imagine.filter.loader.scale_exact:
        parent: ezpublish.image_alias.imagine.filter.loader.scale_exact.base
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScaleExactFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scaleexact" }

    ezpublish.image_alias.imagine.filter.loader.scale_percent:
        parent: ezpublish.image_alias.imagine.filter.loader.scale_exact.base
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ScalePercentFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/scalepercent" }

    ezpublish.image_alias.imagine.filter.loader.crop:
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\CropFilterLoader
        public: false
        calls:
            - [setInnerLoader, ["@liip_imagine.filter.loader.crop"]]
        tags:
            - { name: liip_imagine.filter.loader, loader: "geometry/crop" }

    ezpublish.image_alias.imagine.filter.loader.border:
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\BorderFilterLoader
        public: false
        tags:
            - { name: liip_imagine.filter.loader, loader: "border" }

    ezpublish.image_alias.imagine.filter.loader.reduce_noise:
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\ReduceNoiseFilterLoader
        arguments: ["@ezpublish.image_alias.imagine.filter.reduce_noise"]
        public: false
        tags:
            - { name: liip_imagine.filter.loader, loader: "filter/noise" }

    ezpublish.image_alias.imagine.filter.loader.swirl:
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\SwirlFilterLoader
        arguments: ["@ezpublish.image_alias.imagine.filter.swirl"]
        public: false
        tags:
            - { name: liip_imagine.filter.loader, loader: "filter/swirl" }

    ezpublish.image_alias.imagine.filter.loader.grayscale:
        class: Ibexa\Bundle\Core\Imagine\Filter\Loader\GrayscaleFilterLoader
        public: false
        tags:
            - { name: liip_imagine.filter.loader, loader: "colorspace/gray" }

    ezpublish.image_alias.variation_purger:
        # < platform 2015.05
        # alias: ezpublish.image_alias.variation_purger.legacy_storage_image_file
        # >= platform 2015.05
        alias: ezpublish.image_alias.variation_purger.io

    ezpublish.image_alias.variation_purger.io:
        class: Ibexa\Bundle\Core\Imagine\VariationPurger\IOVariationPurger
        arguments:
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@ezpublish.image_alias.variation_path_generator.alias_directory"
        calls:
            - [setLogger, ["@?logger"]]

    ezpublish.image_alias.variation_purger.legacy_storage_image_file:
        class: Ibexa\Bundle\Core\Imagine\VariationPurger\ImageFileVariationPurger
        arguments:
            - "@ezpublish.image_alias.variation_purger.legacy_storage_image_file.image_file_list"
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@ezpublish.image_alias.variation_path_generator.original_directory"
        calls:
            - [setLogger, ["@?logger"]]

    ezpublish.image_alias.variation_purger.legacy_storage_image_file.image_file_list:
        class: Ibexa\Bundle\Core\Imagine\VariationPurger\LegacyStorageImageFileList
        arguments:
            - "@ezpublish.image_alias.variation_purger.legacy_storage_image_file.image_file_row_reader"
            - '@Ibexa\Core\IO\IOConfigProvider'
            - '@ezpublish.config.resolver'

    ezpublish.image_alias.variation_purger.legacy_storage_image_file.image_file_row_reader:
        class: Ibexa\Bundle\Core\Imagine\VariationPurger\LegacyStorageImageFileRowReader
        arguments:
            $connection: '@ezpublish.persistence.connection'

    ezpublish.image_alias.variation_path_generator:
        # < platform 2015.05
        # alias: ezpublish.image_alias.variation_path_generator.original_directory
        # >= platform 2015.05
        alias: ezpublish.image_alias.variation_path_generator.alias_directory

    ezpublish.image_alias.variation_path_generator.original_directory:
        class: Ibexa\Bundle\Core\Imagine\VariationPathGenerator\OriginalDirectoryVariationPathGenerator

    ezpublish.image_alias.variation_path_generator.alias_directory:
        class: Ibexa\Bundle\Core\Imagine\VariationPathGenerator\AliasDirectoryVariationPathGenerator

    # SPI Aliases
    Ibexa\Contracts\Core\Variation\VariationHandler: '@ezpublish.image_alias.imagine.variation.imagine_alias_generator'
