parameters:
    ezpublish.default_router.non_siteaccess_aware_routes: ['_assetic_', '_wdt', '_profiler', '_configurator_', '_ez_user_hash']
    # characters that may require encoding in the urlalias generator
    ezpublish.urlalias_generator.charmap:
        "\"" : "%22"
        "'" : "%27"
        "<" : "%3C"
        ">" : "%3E"

services:
    ezpublish.chain_router:
        class: Ibexa\Core\MVC\Symfony\Routing\ChainRouter
        arguments: ["@?logger"]
        calls:
            - [setContext, ["@router.request_context"]]

    ezpublish.siteaccess_match_listener:
        class: Ibexa\Core\MVC\Symfony\EventListener\SiteAccessMatchListener
        arguments:
            $siteAccessRouter: '@ezpublish.siteaccess_router'
            $eventDispatcher: '@event_dispatcher'
            $siteAccessMatcherRegistry: '@Ibexa\Bundle\Core\SiteAccess\SiteAccessMatcherRegistryInterface'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\Core\MVC\Symfony\Component\Serializer\CompoundMatcherNormalizer:
        tags:
            - { name: serializer.normalizer }

    ezpublish.url_generator.base:
        class: Ibexa\Core\MVC\Symfony\Routing\Generator
        abstract: true
        calls:
            - [setRequestContext, ["@router.request_context"]]
            - [setSiteAccess, ["@?ezpublish.siteaccess"]]
            - [setSiteAccessRouter, ["@ezpublish.siteaccess_router"]]
            - [setLogger, ["@?logger"]]

    ezpublish.urlalias_router:
        class: Ibexa\Bundle\Core\Routing\UrlAliasRouter
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.api.service.url_alias"
            - "@ezpublish.api.service.content"
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
            - "@?logger"
        calls:
            - [setConfigResolver, ["@ezpublish.config.resolver"]]
        tags:
            - {name: router, priority: 200}

    ezpublish.urlalias_generator:
        class: Ibexa\Core\MVC\Symfony\Routing\Generator\UrlAliasGenerator
        arguments:
            - "@ezpublish.api.repository"
            - "@router.default"
            - "@ezpublish.config.resolver"
            - "%ezpublish.urlalias_generator.charmap%"
        parent: ezpublish.url_generator.base

    Ibexa\Bundle\Core\SiteAccess\SiteAccessMatcherRegistry: ~
    Ibexa\Bundle\Core\SiteAccess\SiteAccessMatcherRegistryInterface:
        alias: 'Ibexa\Bundle\Core\SiteAccess\SiteAccessMatcherRegistry'

    ezpublish.siteaccess.matcher_builder:
        class: Ibexa\Bundle\Core\SiteAccess\MatcherBuilder
        arguments:
            - '@Ibexa\Bundle\Core\SiteAccess\SiteAccessMatcherRegistry'

    ezpublish.siteaccess.provider.static:
        class: Ibexa\Core\MVC\Symfony\SiteAccess\Provider\StaticSiteAccessProvider
        arguments:
            - "%ezpublish.siteaccess.list%"
            - "%ezpublish.siteaccess.groups_by_siteaccess%"
        tags:
            - { name: ezplatform.siteaccess.provider, priority: 10 }

    ezpublish.siteaccess.provider.chain:
        class: Ibexa\Core\MVC\Symfony\SiteAccess\Provider\ChainSiteAccessProvider
        arguments:
            $providers: !tagged ezplatform.siteaccess.provider

    ezpublish.siteaccess.provider:
        alias: ezpublish.siteaccess.provider.chain

    ezpublish.siteaccess_service:
        class: Ibexa\Core\MVC\Symfony\SiteAccess\SiteAccessService
        arguments:
            - "@ezpublish.siteaccess.provider"
            - "@ezpublish.config.resolver"
        calls:
            - [setSiteAccess, ['@ezpublish.siteaccess']]

    Ibexa\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface:
        alias: 'ezpublish.siteaccess_service'

    ezpublish.siteaccess_router:
        class: Ibexa\Core\MVC\Symfony\SiteAccess\Router
        arguments:
            - "@ezpublish.siteaccess.matcher_builder"
            - "@logger"
            - "%ezpublish.siteaccess.default%"
            - "%ezpublish.siteaccess.match_config%"
            - "@ezpublish.siteaccess.provider"
            - 'Ibexa\Core\MVC\Symfony\SiteAccess'
            - "%kernel.debug%"

    ezpublish.siteaccess_listener:
        class: Ibexa\Bundle\Core\EventListener\SiteAccessListener
        arguments:
            - "@ezpublish.siteaccess"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.siteaccess_listener.routing:
        class: Ibexa\Bundle\Core\EventListener\RoutingListener
        arguments: ["@ezpublish.config.resolver", "@ezpublish.urlalias_router", "@ezpublish.urlalias_generator"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.request_redirect_listener:
        class: Ibexa\Bundle\Core\EventListener\RequestEventListener
        arguments:
            - "@ezpublish.config.resolver"
            - "@router"
            - "%ezpublish.siteaccess.default%"
            - "@?logger"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.request_index_listener:
        class: Ibexa\Bundle\Core\EventListener\IndexRequestListener
        arguments:
            - "@ezpublish.config.resolver"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.route_reference.generator:
      class: Ibexa\Core\MVC\Symfony\Routing\Generator\RouteReferenceGenerator
      arguments: ["@event_dispatcher"]
      calls:
        - [setRequestStack, ["@request_stack"]]

    ezpublish.route_reference.listener.language_switch:
        class: Ibexa\Core\MVC\Symfony\EventListener\LanguageSwitchListener
        arguments: ["@ezpublish.translation_helper"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.original_request_listener:
        class: Ibexa\Bundle\Core\EventListener\OriginalRequestListener
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.preview_request_listener:
        class: Ibexa\Bundle\Core\EventListener\PreviewRequestListener
        arguments: ["@request_stack"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.route_reference.listener.content_download:
        class: Ibexa\Bundle\Core\EventListener\ContentDownloadRouteReferenceListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ["@ezpublish.translation_helper"]
