services:
    ezpublish.security.user_provider.username:
        class: Ibexa\Core\MVC\Symfony\Security\User\UsernameProvider
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    ezpublish.security.user_provider.email:
        class: Ibexa\Core\MVC\Symfony\Security\User\EmailProvider
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'

    Ibexa\Core\MVC\Symfony\Security\UserChecker:
        arguments:
            - '@Ibexa\Contracts\Core\Repository\UserService'

    ezpublish.security.voter.core:
        class: Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\CoreVoter
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    ezpublish.security.voter.value_object:
        class: Ibexa\Core\MVC\Symfony\Security\Authorization\Voter\ValueObjectVoter
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        public: false
        tags:
            - { name: security.voter }

    ezpublish.security.controller:
        public: true
        class: Ibexa\Core\MVC\Symfony\Controller\SecurityController
        arguments: ["@twig", "@ezpublish.config.resolver", "@security.authentication_utils"]

    ezpublish.security.login_listener:
        class: Ibexa\Core\MVC\Symfony\Security\EventListener\SecurityListener
        arguments:
            - '@Ibexa\Contracts\Core\Repository\PermissionResolver'
            - '@Ibexa\Contracts\Core\Repository\UserService'
            - "@ezpublish.config.resolver"
            - "@event_dispatcher"
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "%fragment.path%"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.security.user_provider: '@ezpublish.security.user_provider.username'
