parameters:
    # @todo drop once core dependencies stop relying on those parameters
    ezpublish.view_provider.configured.class: Ibexa\Bundle\Core\View\Provider\Configured

    ezpublish.view.matcher_factory.class: Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory

    ezpublish.content_view.viewbase_layout: "@@IbexaCore/viewbase_layout.html.twig"
    ezpublish.content_view.content_block_name: "content"

    ezpublish.twig.extension.filesize.suffixes: ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB']

services:
    ezpublish.twig.extension.content:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
            - "@ezpublish.field_helper"
            - "@?logger"
        tags:
            - {name: twig.extension}

    ezpublish.view_manager:
        class: Ibexa\Bundle\Core\View\Manager
        arguments:
          - "@twig"
          - "@event_dispatcher"
          - "@ezpublish.siteaccessaware.repository"
          - "@ezpublish.config.resolver"
          - "%ezpublish.content_view.viewbase_layout%"
          - "@ezpublish.view.configurator"
          - "@?logger"

    Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry: ~

    ezpublish.content_view_provider.configured:
        class: Ibexa\Bundle\Core\View\Provider\Configured
        arguments: ["@ezpublish.content_view.matcher_factory"]
        tags:
            - {name: ezpublish.view_provider, type: 'Ibexa\Core\MVC\Symfony\View\ContentView', priority: 10}

    ezpublish.content_view.matcher_factory:
        class: Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'Ibexa\Core\MVC\Symfony\Matcher\ContentBased'

    ezpublish.content_view.matcher_factory.dynamically_configured:
        class: Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ezpublish.content_view.matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ezpublish.content_view.matcher_factory.dynamically_configured.inner'
            $configResolver: '@ezpublish.config.resolver'
            $parameterName: content_view

    ezpublish.content_view_provider.default_configured:
        class: Ibexa\Bundle\Core\View\Provider\Configured
        arguments: ["@ezpublish.content_view.default_matcher_factory"]
        tags:
            - {name: ezpublish.view_provider, type: 'Ibexa\Core\MVC\Symfony\View\ContentView', priority: -1}

    ezpublish.content_view.default_matcher_factory:
        class: Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'Ibexa\Core\MVC\Symfony\Matcher\ContentBased'

    ezpublish.content_view.default_matcher_factory.dynamically_configured:
        class: Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ezpublish.content_view.default_matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ezpublish.content_view.default_matcher_factory.dynamically_configured.inner'
            $configResolver: '@ezpublish.config.resolver'
            $parameterName: content_view_defaults

    ezpublish.location_view_provider.configured:
        class: Ibexa\Bundle\Core\View\Provider\Configured
        arguments: ["@ezpublish.location_view.matcher_factory"]
        tags:
            - {name: ezpublish.view_provider, type: 'Ibexa\Core\MVC\Symfony\View\ContentView', priority: 10}

    ezpublish.location_view.matcher_factory:
        class: Ibexa\Bundle\Core\Matcher\ServiceAwareMatcherFactory
        arguments:
            - '@Ibexa\Bundle\Core\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'Ibexa\Core\MVC\Symfony\Matcher\ContentBased'

    ezpublish.location_view.matcher_factory.dynamically_configured:
        class: Ibexa\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ezpublish.location_view.matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ezpublish.location_view.matcher_factory.dynamically_configured.inner'
            $configResolver: '@ezpublish.config.resolver'
            $parameterName: location_view

    ezpublish.templating.global_helper.core:
        class: Ibexa\Core\MVC\Symfony\Templating\GlobalHelper
        arguments: ["@ezpublish.config.resolver", "@ezpublish.siteaccessaware.service.location", "@router", "@ezpublish.translation_helper"]
        calls:
            - [setRequestStack, ["@request_stack"]]

    Ibexa\Core\MVC\Symfony\Templating\GlobalHelper:
        alias: ezpublish.templating.global_helper.core

    ezpublish.templating.global_helper:
        alias: ezpublish.templating.global_helper.core

    ezpublish.twig.extension.core:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\CoreExtension
        arguments: ["@ezpublish.templating.global_helper"]
        tags:
            - {name: twig.extension}

    ezpublish.twig.extension.filesize:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\FileSizeExtension
        arguments: ["@translator", "%ezpublish.twig.extension.filesize.suffixes%", "@ezpublish.config.resolver", "@ezpublish.locale.converter" ]
        tags:
            - {name: twig.extension}

    ezpublish.templating.extension.routing:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\RoutingExtension
        arguments: ["@ezpublish.route_reference.generator", "@router"]
        tags:
            - {name: twig.extension}

    Ibexa\Core\MVC\Symfony\Templating\Twig\ResourceProvider:
        arguments:
            $configResolver: '@ezpublish.config.resolver'

    ezpublish.templating.field_block_renderer.twig:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\FieldBlockRenderer
        arguments:
            $twig: '@twig'
            $resourceProvider: '@Ibexa\Core\MVC\Symfony\Templating\Twig\ResourceProvider'
            $baseTemplate: '%ezpublish.content_view.viewbase_layout%'

    ezpublish.templating.field_block_renderer:
        alias: ezpublish.templating.field_block_renderer.twig

    ezpublish.twig.extension.field_rendering:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\FieldRenderingExtension
        arguments:
            - "@ezpublish.templating.field_block_renderer"
            - "@ezpublish.fieldType.parameterProviderRegistry"
            - "@ezpublish.translation_helper"
        tags:
            - { name: twig.extension }

    Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\QueryRenderingExtension:
        arguments:
            - '@fragment.handler'
        tags:
            - { name: twig.extension }

    Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\RenderExtension:
        arguments:
            $renderStrategy: '@Ibexa\Contracts\Core\MVC\Templating\RenderStrategy'
            $eventDispatcher: '@event_dispatcher'
        tags:
            - { name: twig.extension }

    Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\RenderContentExtension:
        arguments:
            $renderContentStrategy: '@Ibexa\Core\MVC\Symfony\Templating\RenderContentStrategy'
            $eventDispatcher: '@event_dispatcher'
        tags:
            - { name: twig.extension }

    Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\RenderLocationExtension:
        arguments:
            $renderLocationStrategy: '@Ibexa\Core\MVC\Symfony\Templating\RenderLocationStrategy'
            $eventDispatcher: '@event_dispatcher'
        tags:
            - { name: twig.extension }

    Ibexa\Core\MVC\Symfony\Templating\RenderStrategy:
        arguments:
            $strategies: !tagged_iterator ibexa.platform.render.strategy

    Ibexa\Contracts\Core\MVC\Templating\RenderStrategy: '@Ibexa\Core\MVC\Symfony\Templating\RenderStrategy'

    Ibexa\Core\MVC\Symfony\Templating\RenderContentStrategy:
        arguments:
            $fragmentRenderers: !tagged_iterator kernel.fragment_renderer
            $defaultRenderer: !php/const Ibexa\Bundle\Core\Fragment\DirectFragmentRenderer::NAME
            $siteAccess: '@ezpublish.siteaccess'
            $requestStack: '@request_stack'
        tags:
            - { name: ibexa.platform.render.strategy }

    Ibexa\Core\MVC\Symfony\Templating\RenderLocationStrategy:
        arguments:
            $fragmentRenderers: !tagged_iterator kernel.fragment_renderer
            $defaultRenderer: !php/const Ibexa\Bundle\Core\Fragment\DirectFragmentRenderer::NAME
            $siteAccess: '@ezpublish.siteaccess'
            $requestStack: '@request_stack'
        tags:
            - { name: ibexa.platform.render.strategy }

    ezpublish.twig.extension.image:
        class: Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\ImageExtension
        arguments:
            - '@ezpublish.fieldType.ezimage.variation_service'
            - '@Ibexa\Core\FieldType\ImageAsset\AssetMapper'
        tags:
            - { name: twig.extension }

    ezpublish.view.custom_location_controller_checker:
        class: Ibexa\Core\MVC\Symfony\View\CustomLocationControllerChecker

    ezpublish.view_provider.registry:
        class: Ibexa\Core\MVC\Symfony\View\Provider\Registry

    ezpublish.view.configurator:
        class: Ibexa\Core\MVC\Symfony\View\Configurator\ViewProvider
        arguments: ["@ezpublish.view_provider.registry"]

    ezpublish.view_builder.registry:
        class: Ibexa\Core\MVC\Symfony\View\Builder\Registry\ControllerMatch
        arguments:
            $viewBuilders: !tagged_iterator { tag: ibexa.view_builder }

    ezpublish.view_builder.content:
        class: Ibexa\Core\MVC\Symfony\View\Builder\ContentViewBuilder
        arguments:
            - "@ezpublish.siteaccessaware.repository"
            - "@ezpublish.view.configurator"
            - "@ezpublish.view.view_parameters.injector.dispatcher"
            - "@request_stack"
            - "@ezpublish.content_info_location_loader.main"
        tags:
            - { name: ibexa.view_builder }

    ezpublish.view.builder_parameter_collector.request_attributes:
        class: Ibexa\Core\MVC\Symfony\View\Builder\ParametersFilter\RequestAttributes
        tags:
            - {name: kernel.event_subscriber}

    ezpublish.view.template_renderer:
        class: Ibexa\Core\MVC\Symfony\View\Renderer\TemplateRenderer
        arguments: ["@twig", "@event_dispatcher"]

    ezpublish.view.renderer_listener:
        class: Ibexa\Bundle\Core\EventListener\ViewRendererListener
        arguments: ["@ezpublish.view.template_renderer"]
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.view_parameters.injector.dispatcher:
        class: Ibexa\Core\MVC\Symfony\View\ParametersInjector\EventDispatcherInjector
        arguments: ["@event_dispatcher"]

    ezpublish.view.view_parameters.injector.custom_parameters:
        class: Ibexa\Core\MVC\Symfony\View\ParametersInjector\CustomParameters
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.view_parameters.injector.embed_object_parameters:
        class: Ibexa\Core\MVC\Symfony\View\ParametersInjector\EmbedObjectParameters
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.view_parameters.injector.no_layout:
        class: Ibexa\Core\MVC\Symfony\View\ParametersInjector\NoLayout
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.view_parameters.injector.value_objects_ids:
        class: Ibexa\Core\MVC\Symfony\View\ParametersInjector\ValueObjectsIds
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.view_parameters.injector.viewbase_layout:
        class: Ibexa\Core\MVC\Symfony\View\ParametersInjector\ViewbaseLayout
        arguments:
            - "%ezpublish.content_view.viewbase_layout%"
            - "@ezpublish.config.resolver"
        tags:
            - { name: kernel.event_subscriber }

    ezpublish.view.cache_response_listener:
        class: Ibexa\Bundle\Core\EventListener\CacheViewResponseListener
        arguments:
            $configResolver: '@ezpublish.config.resolver'
        tags:
            - { name: kernel.event_subscriber }

    Ibexa\Core\MVC\Symfony\Templating\Twig\Extension\DataAttributesExtension:
        autoconfigure: true
        public: false

    Ibexa\Bundle\Core\Templating\Twig\ContextAwareTwigVariablesExtension:
        arguments:
            $configResolver: "@ezpublish.config.resolver"
        tags:
            - { name: twig.extension }

    Ibexa\Core\MVC\Symfony\EventListener\ContentViewTwigVariablesSubscriber:
        autoconfigure: true
        autowire: true

    Ibexa\Core\MVC\Symfony\View\GenericVariableProviderRegistry:
        arguments:
            $twigVariableProviders: !tagged ezplatform.view.variable_provider

    Ibexa\Core\MVC\Symfony\View\VariableProviderRegistry: '@Ibexa\Core\MVC\Symfony\View\GenericVariableProviderRegistry'
