services:
    _defaults:
        public: false
        autoconfigure: true
        autowire: true

    Ibexa\Core\FieldType\Image\ImageThumbnailStrategy:
        arguments:
            $variationHandler: '@Ibexa\Contracts\Core\Variation\VariationHandler'
            $variationName: 'medium'

    Ibexa\Core\FieldType\Image\ImageThumbnailProxyStrategy:
        decorates: Ibexa\Core\FieldType\Image\ImageThumbnailStrategy
        arguments:
            $imageThumbnailStrategy: '@.inner'
            $proxyGenerator: '@Ibexa\Core\Repository\ProxyFactory\ProxyGeneratorInterface'

    Ibexa\Core\FieldType\ImageAsset\ImageAssetThumbnailStrategy:
        lazy: true
        arguments:
            $thumbnailStrategy: '@Ibexa\Core\Repository\Strategy\ContentThumbnail\ThumbnailChainStrategy'
            $contentService: '@ezpublish.api.service.content'

    Ibexa\Core\Repository\Strategy\ContentThumbnail\Field\ContentFieldStrategy:
        arguments:
            $strategies:
                ezimage: '@Ibexa\Core\FieldType\Image\ImageThumbnailStrategy'
                ezimageasset: '@Ibexa\Core\FieldType\ImageAsset\ImageAssetThumbnailStrategy'

    Ibexa\Core\Repository\Strategy\ContentThumbnail\FirstMatchingFieldStrategy:
        arguments:
            $fieldTypeService: '@ezpublish.api.service.field_type'
            $contentFieldStrategy: '@Ibexa\Core\Repository\Strategy\ContentThumbnail\Field\ContentFieldStrategy'
        tags:
            - { name: ezplatform.spi.content.thumbnail_strategy, priority: 0 }

    Ibexa\Core\Repository\Strategy\ContentThumbnail\ThumbnailChainStrategy:
        arguments:
            $strategies: !tagged_iterator ezplatform.spi.content.thumbnail_strategy
