services:
    ezpublish.console.command.regenerate_url_aliases:
        class: eZ\Bundle\EzPublishCoreBundle\Command\RegenerateUrlAliasesCommand
        arguments:
            # intentionally passing inner repository to avoid sending Events due to performance issues
            - '@ezpublish.api.inner_repository'
            - '@?logger'
        tags:
            - { name: console.command }

    ezplatform.core.command.debug_config_resolver:
        class: eZ\Bundle\EzPublishCoreBundle\Command\DebugConfigResolverCommand
        arguments:
            - "@ezpublish.config.resolver"
            - "@ezpublish.siteaccess"
        tags:
            - { name: console.command }

    ezplatform.core.command.check_urls:
        class: eZ\Bundle\EzPublishCoreBundle\Command\CheckURLsCommand
        arguments:
            - '@eZ\Publish\API\Repository\UserService'
            - '@eZ\Publish\API\Repository\PermissionResolver'
            - '@eZ\Publish\API\Repository\URLService'
            - '@ezpublish.url_checker'
        tags:
            - { name: console.command }

    eZ\Bundle\EzPublishCoreBundle\Command\UpdateTimestampsToUTCCommand:
        arguments:
            - '@ezpublish.api.search_engine.legacy.connection'
        tags:
            - { name: console.command }

    eZ\Bundle\EzPublishCoreBundle\Command\ReindexCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $searchIndexer: '@ezpublish.spi.search.indexer'
            $locationHandler: '@ezpublish.spi.persistence.location_handler'
            $siteaccess: '@ezpublish.siteaccess'
            $env: '%kernel.environment%'
            $projectDir: '%kernel.project_dir%'
            $isDebug: '%kernel.debug%'
        tags:
            - { name: console.command }

    eZ\Bundle\EzPublishCoreBundle\Command\NormalizeImagesPathsCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $connection: '@ezpublish.persistence.connection'
            $imageGateway: '@ezpublish.fieldType.ezimage.storage_gateway'
            $ioService: '@ezpublish.fieldType.ezimage.io_service'
        tags:
            - { name: console.command }

    Ibexa\Bundle\Core\Command\ExpireUserPasswordsCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $userHandler: '@ezpublish.spi.persistence.legacy.user.handler'
        tags:
            - { name: console.command }
