services:
    # Parameter providers
    ezpublish.fieldType.parameterProviderRegistry:
        class: eZ\Publish\Core\MVC\Symfony\FieldType\View\ParameterProviderRegistry

    ezpublish.fieldType.ezdatetime.parameterProvider:
        class: eZ\Publish\Core\MVC\Symfony\FieldType\View\ParameterProvider\LocaleParameterProvider
        arguments: ["@ezpublish.locale.converter"]
        calls:
            - [setRequestStack, ["@request_stack"]]
        tags:
            - {name: ezplatform.field_type.parameter_provider, alias: ezdatetime}
            - {name: ezplatform.field_type.parameter_provider, alias: ezdate}
            - {name: ezplatform.field_type.parameter_provider, alias: eztime}

    ezpublish.fieldType.ezobjectrelation.parameterProvider:
        class: eZ\Publish\Core\MVC\Symfony\FieldType\Relation\ParameterProvider
        arguments:
            - "@ezpublish.api.service.content"
        tags:
            - {name: ezplatform.field_type.parameter_provider, alias: ezobjectrelation}

    ezpublish.fieldType.ezobjectrelationlist.parameterProvider:
        class: eZ\Publish\Core\MVC\Symfony\FieldType\RelationList\ParameterProvider
        arguments:
            - "@ezpublish.api.service.content"
        tags:
            - {name: ezplatform.field_type.parameter_provider, alias: ezobjectrelationlist}

    ezpublish.fieldType.ezimageasset.parameterProvider:
        class: eZ\Publish\Core\MVC\Symfony\FieldType\ImageAsset\ParameterProvider
        lazy: true
        arguments:
            - "@ezpublish.siteaccessaware.repository"
        tags:
            - {name: ezplatform.field_type.parameter_provider, alias: ezimageasset}

    eZ\Publish\Core\MVC\Symfony\FieldType\User\ParameterProvider:
        lazy: true
        arguments:
            - "@ezpublish.api.service.user"
        tags:
            - {name: ezplatform.field_type.parameter_provider, alias: ezuser}

    # Image
    ezpublish.fieldType.ezimage.io_service:
        class: eZ\Publish\Core\FieldType\Image\IO\Legacy
        arguments:
            - "@ezpublish.fieldType.ezimage.io_service.published"
            - "@ezpublish.fieldType.ezimage.io_service.draft"
            - "@ezpublish.fieldType.ezimage.io_service.options_provider"
        # Required by ezpublish.core.io.stream_file_listener. Request listeners are initialized very early.
        lazy: true

    ezpublish.fieldType.ezimage.io_service.options_provider:
        class: eZ\Publish\Core\FieldType\Image\IO\OptionsProvider
        arguments:
            $configResolver: '@ezpublish.config.resolver'

    # Image alias generator
    ezpublish.fieldType.ezimage.variation_service:
        alias: ezpublish.image_alias.imagine.alias_generator.image_asset

    ezpublish.fieldType.ezimage.io_service.published:
        class: eZ\Publish\Core\IO\ConfigScopeChangeAwareIOService
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $innerIOService: '@ezpublish.core.io.service'
            $prefixParameterName: 'image.published_images_dir'

    ezpublish.fieldType.ezimage.io_service.draft:
        class: eZ\Publish\Core\IO\ConfigScopeChangeAwareIOService
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $innerIOService: '@ezpublish.core.io.service'
            $prefixParameterName: 'image.versioned_images_dir'

    ezpublish.fieldType.ezimage.pathGenerator:
        class: eZ\Publish\Core\FieldType\Image\PathGenerator\LegacyPathGenerator

    ezpublish.fieldType.validator.black_list:
        class: eZ\Publish\Core\FieldType\Validator\FileExtensionBlackListValidator
        arguments:
            - '@ezpublish.config.resolver'

    ezpublish.fieldType.validator.image:
        class: eZ\Publish\Core\FieldType\Validator\ImageValidator

    # BinaryFile
    ezpublish.fieldType.ezbinaryfile.io_service:
        class: eZ\Publish\Core\IO\ConfigScopeChangeAwareIOService
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $innerIOService: '@ezpublish.core.io.service'
            $prefixParameterName: 'binary_dir'

    ezpublish.fieldType.ezbinaryfile.pathGenerator:
        class: eZ\Publish\Core\FieldType\BinaryBase\PathGenerator\LegacyPathGenerator

    # Will be added to binaryfile & mediafile external storage handlers by a compiler pass
    ezpublish.fieldType.ezbinarybase.download_url_generator:
        public: true # @todo should be private
        class: eZ\Publish\Core\MVC\Symfony\FieldType\BinaryBase\ContentDownloadUrlGenerator
        arguments: ["@router"]

    # Symfony 3.4+ service definitions:
    eZ\Publish\Core\FieldType\ImageAsset\AssetMapper:
        lazy: true
        arguments:
            $contentService: '@ezpublish.api.service.content'
            $locationService: '@ezpublish.api.service.location'
            $contentTypeService: '@ezpublish.api.service.content_type'
            $configResolver: 'ezpublish.config.resolver'
