services:
    EzSystems\PlatformInstallerBundle\Event\Subscriber\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml")'

    EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller:
        abstract: true
        arguments: ["@ezpublish.persistence.connection"]
        lazy: true

    EzSystems\PlatformInstallerBundle\Installer\CoreInstaller:
        autowire: true
        parent: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
        tags:
            - { name: ezplatform.installer, type: clean } # left for BC, should be removed in Ibexa 4.0
            - { name: ezplatform.installer, type: ibexa-oss }

    EzSystems\PlatformInstallerBundle\Command\InstallPlatformCommand:
        arguments:
            $connection: "@ezpublish.persistence.connection"
            $installers: []
            $cachePool: '@ezpublish.cache_pool'
            $environment: "%kernel.environment%"
            $repositoryConfigurationProvider: '@ezpublish.api.repository_configuration_provider'
        tags:
            - { name: console.command }

    EzSystems\PlatformInstallerBundle\Command\ValidatePasswordHashesCommand:
        arguments:
            $userStorage: '@ezpublish.fieldType.ezuser.externalStorage'
            $passwordHashService: '@eZ\Publish\API\Repository\PasswordHashService'
        tags:
            - { name: console.command }
