services:
    Ibexa\Bundle\RepositoryInstaller\Event\Subscriber\BuildSchemaSubscriber:
        autoconfigure: true
        public: false
        arguments:
            - '@=service("kernel").locateResource("@IbexaCoreBundle/Resources/config/storage/legacy/schema.yaml")'

    Ibexa\Bundle\RepositoryInstaller\Installer\DbBasedInstaller:
        abstract: true
        arguments: ["@ezpublish.persistence.connection"]
        lazy: true

    Ibexa\Bundle\RepositoryInstaller\Installer\CoreInstaller:
        autowire: true
        parent: Ibexa\Bundle\RepositoryInstaller\Installer\DbBasedInstaller
        tags:
            - { name: ezplatform.installer, type: clean } # left for BC, should be removed in Ibexa 4.0
            - { name: ezplatform.installer, type: ibexa-oss }

    Ibexa\Bundle\RepositoryInstaller\Command\InstallPlatformCommand:
        arguments:
            $connection: "@ezpublish.persistence.connection"
            $installers: []
            $cachePool: '@ezpublish.cache_pool'
            $environment: "%kernel.environment%"
            $repositoryConfigurationProvider: '@ezpublish.api.repository_configuration_provider'
        tags:
            - { name: console.command }

    Ibexa\Bundle\RepositoryInstaller\Command\ValidatePasswordHashesCommand:
        arguments:
            $userStorage: '@ezpublish.fieldType.ezuser.externalStorage'
            $passwordHashService: '@Ibexa\Contracts\Core\Repository\PasswordHashService'
        tags:
            - { name: console.command }
